config/routes.rb
Rails.application.routes.draw do
  get 'hello_world', to: 'hello_world#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Homepage
  root to: 'pages#home', as: 'about'

  # Static Pages
  get '/skills',        to: 'pages#skills',         as: 'skills'
  get '/work',          to: 'pages#work',           as: 'work'
  get '/about-site',    to: 'pages#about_site',     as: 'about_site'

  # Work Items
  get '/work/muh-invite-case-study',      to: 'work#muh_invite',  as: 'work_muh_invite'
  get '/work/freo-royale-animation',      to: 'work#anomaly',     as: 'work_anomaly'
  get '/work/bates-saddles',              to: 'work#bates',       as: 'work_bates'
  get '/work/twoofthree-animation',       to: 'work#glitched',    as: 'work_glitched'
  get '/work/izo-photography',            to: 'work#izo',         as: 'work_izo'
  get '/work/star-international',         to: 'work#star',        as: 'work_star'
  get '/work/wa-exclusive-meats',         to: 'work#wa_meats',    as: 'work_wa_meats'
  get '/work/wintec-saddles',             to: 'work#wintec',      as: 'work_wintec'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/work_controller.rb
class WorkController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: true) %>

app/views/pages/skills.html.erb
<% content_for :body_class, "skills " %>
<% content_for :title, "Skills" %>
<% content_for :description, "A run down of the tools and knowledge I've acquired." %>

<div class="l__g-fluid-100vh">

  <div class="[ c-mugshot ] u-l__f-center">
    <div class="[ c-mugshot__coaster ]">
      <%= image_tag("jakegonzales--astronaut.png", class: "c-mugshot__mug") %>
    </div>
  </div>

  <div class="l__f-2-row">

    <%= render 'shared/nav_main' %>

    <section class="c-article l__f-2-row-1   l__f-col-justify-start"> 

      <header class="u-spacers l__f">
        <div class="u-space-md u-max-width-copy">
          <h1 class="h1-blocked-white">Skills Summary</h1>
        </div>
        <div class="u-space-md">
          <%= link_to about_path, class: '[ c-button c-button-icon ]' do %>
            <i class="[ c-button-icon__icon ] fa fa-arrow-up"></i>
            <span class="[ c-button-icon__text ]">About</span>
          <% end %>
        </div>
      </header>

      <div class="u-spacers u-negative u-negative--red u-width-100" style="flex: 1;">

        <div class="u-space-stack-md u-spacers u-max-width-copy">

          <h2>Frontend Design</h2>
          <p>I build websites with <strong>CSS3</strong>, <strong>SCSS</strong>, <strong>HTML5</strong>, and <strong>responsive design</strong>. I've also started experimenting with <strong>intrinsic design</strong> with <strong>CSS Grid</strong> and <strong>Flexbox</strong>. I don't write a lot of JS but it's on my road map to get stuck into more React and ES6.</p> 
          <p>I predominately use <strong>Wordpress</strong> combined with <strong>Advanced Custom Fields</strong> as my CMS but I've built sites with <strong>Craft CMS</strong> and <strong>Ruby on Rails</strong> as well.</p>
          <p>I design websites with a mixture of <strong>Photoshop</strong>, <strong>Sketch</strong>, and <strong>Illustrator</strong>.</p>

          <h2>User Experience Design</h2>
          <p>I can help with user journey's, card sorting, content/component auditing, and generally designing/improving the experience for the user.</p>
          <p>I prototype websites with <strong>Photoshop</strong>, <strong>Sketch</strong>, and <strong>Adobe XD</strong>; as well as good old pen and paper. I ask a lot of questions and can’t help but deep dive into what makes a business and its clients tick.</p>
          <p>Making life easier for people is my real passion. Understanding their needs and wants and how best to deliver that to them on the web and in the real world makes me Buzz.</p>
          
        </div>

        <div class="u-space-lg l__f-align-center">
          <%= link_to work_path, class: '[ c-button c-button-icon ]' do %>
            <i class="[ c-button-icon__icon ] fa fa-arrow-right"></i>
            <span class="[ c-button-icon__text ]">Browse Work</span>
          <% end %>
        </div>

      </div>

    </section>

    <div class="l__f-2-row-2 u-negative--blue"></div>



  </div>

</div>

app/views/pages/work.html.erb
<% content_for :body_class, "work " %>
<% content_for :title, "Work" %>
<% content_for :description, "A few of my favourite projects I've worked on." %>

<div class="l__g-2-col">

  <div class="l__f-2-row">
    <%= render 'shared/nav_main' %>

    <ol class="l__tesseract l__f-align-center">

      <li class="l__tesseract__obvious poster">

          <figure class="poster__image u-image-loader">
            <%= link_to work_wintec_path, :title => "Wintec Saddles Web Project" do %>
              <div style="--aspect-ratio:800/400;">
                <%= image_tag("work/thumb-wintec-saddles.jpg", alt: "A Wintec Synthetic Saddle, Black") %>
              </div>
            <% end %>
          </figure>
          <figcaption class="poster__text u-spacers-static">
            <header class="text__header">
              <span class="u-space">
                <time datetime="2013">2013</time> → <time datetime="2018">2018</time>
              </span>
              <%= link_to work_wintec_path, :title => "Wintec Saddles Web Project" do %><h1 class="u-space">The World’s Number One Synthetic Saddle: Wintec Saddles.</h1><% end %>
            </header>
            <div class="text__body u-space">
              <ul class="c-tag-list">
                <li class="c-tag-list__tag">Wordpress</li>
                <li class="c-tag-list__tag">Frontend</li>
                <li class="c-tag-list__tag">Design</li>
                <li class="c-tag-list__tag">Photoshop</li>
              </ul>
            </div>
          </figcaption>

      </li>

      <li class="l__tesseract__simple poster u-rtl">

        <figure class="poster__image u-image-loader">
            <%= link_to work_bates_path, :title => "Bates Saddles Web Project" do %>
              <div style="--aspect-ratio:800/400;">
                <%= image_tag("work/thumb-bates-saddles.jpg", alt: "A Bates Saddle, Adjustable Ergonomic Stirrup Bar Closeup") %>
              </div>
            <% end %>
          </figure>
          <figcaption class="poster__text u-spacers-static u-ltr">
            <header class="text__header">
              <span class="u-space">
                <time datetime="2013">2013</time> → <time datetime="2018">2018</time>
              </span>
              <%= link_to work_bates_path, :title => "Bates Saddles Web Project" do %><h1 class="u-space">The most saddle patents globally: Bates Saddles.</h1><% end %>
            </header>
            <div class="text__body u-space">
              <ul class="c-tag-list">
                <li class="c-tag-list__tag">Wordpress</li>
                <li class="c-tag-list__tag">Frontend</li>
                <li class="c-tag-list__tag">Design</li>
                <li class="c-tag-list__tag">Photoshop</li>
              </ul>
            </div>
          </figcaption>
      </li>

      <li class="l__tesseract__simple poster u-rtl">

        <figure class="poster__image u-image-loader">
            <%= link_to work_izo_path, :title => "IZO Photography Web Project" do %>
              <div style="--aspect-ratio:800/400;">
                <%= image_tag("work/thumb-izo-photography.jpg", alt: "A hexagonal treatment for images on izo.com.au") %>
              </div>
            <% end %>
          </figure>
          <figcaption class="poster__text u-spacers-static u-ltr">
            <header class="text__header">
              <span class="u-space">
                <time datetime="2017">2017</time>
              </span>
              <%= link_to work_izo_path, :title => "IZO Photography Web Project" do %><h1 class="u-space">Photographer of the Year: IZO Photography</h1><% end %>
            </header>
            <div class="text__body u-space">
              <ul class="c-tag-list">
                <li class="c-tag-list__tag">Wordpress</li>
                <li class="c-tag-list__tag">Frontend</li>
                <li class="c-tag-list__tag">UX</li>
                <li class="c-tag-list__tag">jQuery</li>
              </ul>
            </div>
          </figcaption>
      </li>

      <li class="l__tesseract__obvious poster u-rtl">

        <figure class="poster__image u-image-loader">
            <%= link_to work_star_path, :title => "Star International Web Project" do %>
              <div style="--aspect-ratio:800/400;">
                <%= image_tag("work/thumb-star-international.jpg", alt: "A closeup of a text treatment on starinternational.com.au") %>
              </div>
            <% end %>
          </figure>
          <figcaption class="poster__text u-spacers-static u-ltr">
            <header class="text__header">
              <span class="u-space">
                <time datetime="2018">2018</time>
              </span>
              <%= link_to work_star_path, :title => "Star International Web Project" do %><h1 class="u-space">Trusted By The Australian Defence Industry: Star International.</h1><% end %>
            </header>
            <div class="text__body u-space">
              <ul class="c-tag-list">
                <li class="c-tag-list__tag">Craft CMS</li>
                <li class="c-tag-list__tag">Frontend</li>
                <li class="c-tag-list__tag">UX</li>
                <li class="c-tag-list__tag">SVG</li>
                <li class="c-tag-list__tag">CSS Grid</li>
                <li class="c-tag-list__tag">Animation</li>
              </ul>
            </div>
          </figcaption>
      </li>

      <li class="l__tesseract__obvious poster">

        <figure class="poster__image u-image-loader">
            <%= link_to work_muh_invite_path, :title => "Technical Case Study: Christmas Invite: Macquarie University Hospital Web Project, Technical Case Study" do %>
              <div style="--aspect-ratio:800/400;">
                <%= image_tag("work/thumb-macquire-university-hospital.jpg", alt: "Text saying 'Open the garden gate' on a forest background") %>
              </div>
            <% end %>
          </figure>
          <figcaption class="poster__text u-spacers-static">
            <header class="text__header">
              <span class="u-space">
                <time datetime="2017">2017</time>
              </span>
              <%= link_to work_muh_invite_path, :title => "Christmas Invite: Macquarie University Hospital Web Project, Technical Case Study" do %><h1 class="u-space">A Dreamy Botanical Adventure Christmas Party Web Invite</h1><% end %>
            </header>
            <div class="text__body u-space">
              <ul class="c-tag-list">
                <li class="c-tag-list__tag c-tag-list__tag-alt">Case Study</li>
                <li class="c-tag-list__tag">Frontend</li>
                <li class="c-tag-list__tag">SVG</li>
                <li class="c-tag-list__tag">Animation</li>
              </ul>
            </div>
          </figcaption>
      </li>

      <li class="l__tesseract__simple poster">

        <figure class="poster__image u-image-loader">
            <%= link_to work_wa_meats_path, :title => "WA Exclusive Meats Web Project" do %>
              <div style="--aspect-ratio:800/400;">
                <%= image_tag("work/thumb-wa-exclusive-meats.jpg", alt: "An old photo showing the first customers to a butcher on Constitution Street, Bunbury, 1993") %>
              </div>
            <% end %>
          </figure>
          <figcaption class="poster__text u-spacers-static">
            <header class="text__header">
              <span class="u-space">
                <time datetime="2016">2016</time>
              </span>
              <%= link_to work_wa_meats_path, :title => "WA Exclusive Meats Web Project" do %><h1 class="u-space">Over 80 years serving the community: WA Exclusive Meats</h1><% end %>
            </header>
            <div class="text__body u-space">
              <ul class="c-tag-list">
                <li class="c-tag-list__tag">Wordpress</li>
                <li class="c-tag-list__tag">Frontend</li>
                <li class="c-tag-list__tag">UX</li>
                <li class="c-tag-list__tag">Illustration</li>
              </ul>
            </div>
          </figcaption>
      </li>

      <li class="l__tesseract__simple poster u-rtl">

        <figure class="poster__image u-image-loader">
          <%= link_to work_anomaly_path, :title => "Liam Dee Art Animated" do %>
            <div style="--aspect-ratio:800/400;">
              <%= image_tag("work/thumb-freo-glitch.jpg", alt: "Closeup of an artwork by Liam Dee") %>
            </div>
          <% end %>
        </figure>
        <figcaption class="poster__text u-spacers-static u-ltr">
          <header class="text__header">
            <span class="u-space">
              <time datetime="2015">2015</time>
            </span>
            <%= link_to work_anomaly_path, :title => "Liam Dee Art Animated" do %><h1 class="u-space">Bringing Liam Dee's Artwork to Life</h1><% end %>
          </header>
          <div class="text__body u-space">
            <ul class="c-tag-list">
              <li class="c-tag-list__tag">CSS Animation</li>
              <li class="c-tag-list__tag">Photoshop</li>
            </ul>
          </div>
        </figcaption>
      </li>

      <li class="l__tesseract__simple poster u-rtl">

        <figure class="poster__image u-image-loader">
          <%= link_to work_glitched_path, :title => "Glitched Computer Screen Animation for Two Of Three" do %>
            <div style="--aspect-ratio:800/400;">
              <%= image_tag("work/thumb-glitch-horror.jpg", alt: "Closeup of an illustrated computer screen and keyboard") %>
            </div>
          <% end %>
        </figure>
        <figcaption class="poster__text u-spacers-static u-ltr">
          <header class="text__header">
            <span class="u-space">
              <time datetime="2017">2017</time>
            </span>
            <%= link_to work_glitched_path, :title => "Glitched Computer Screen Animation for Two Of Three" do %><h1 class="u-space">Glitched Horror</h1><% end %>
          </header>
          <div class="text__body u-space">
            <ul class="c-tag-list">
              <li class="c-tag-list__tag">CSS Animation</li>
            </ul>
          </div>
        </figcaption>
      </li>
      
    </ol>  

    <div class="u-space-lg l__f-align-center">
      <div class="u-spacers l__f">
        <div class="u-space">
          <%= link_to skills_path, class: 'c-button c-button-icon' do %>
            <i class="c-button-icon__icon fa fa-arrow-left"></i>
            <span class="c-button-icon__text">Skills</span>
          <% end %>
        </div>
        <div class="u-space">
          <%= link_to about_site_path, class: 'c-button c-button-icon' do %>
            <i class="c-button-icon__icon fa fa-arrow-right"></i>
            <span class="c-button-icon__text">About This Site</span>
          <% end %>
        </div>
      </div>
    </div>

  </div>

  

</div>

app/views/shared/_nav_main.html.erb
<nav class="c-navigation-main u-spacers">
  <span class="u-space-stack l__menu-right">
    <%= link_to "About", '/', title: "", :class => "c-navigation-main__link #{current_page?('/') ? 'c-navigation-main__link--active' : ''}"  %>
    <%= link_to "Skills", skills_path, title: "", :class => "c-navigation-main__link #{current_page?('/skills') ? 'c-navigation-main__link--active' : ''}"  %>
    <%= link_to "Work", work_path, title: "", :class => "c-navigation-main__link #{request.fullpath.start_with?('/work') ? 'c-navigation-main__link--active' : ''}"  %>
    <a href="https://twitter.com/jakegonzales" class="c-navigation-main__link-icon c-navigation-main__link"><i class="fab fa-twitter"></i></a>
    <a href="mailto:comms@jakegonzales.com" class="u-email-copy-btn c-navigation-main__link-icon c-navigation-main__link"><i class="far fa-envelope"></i><span class="u-email-copy-address u-js--hidden">jakeegonzales@gmail.com</span></a>
  </span>
</nav>

app/views/work/anomaly.html.erb
<% content_for :body_class, "work-single " %>
<% content_for :title, "Work: Bringing Liam Dee's Artwork to Life" %>
<% content_for :description, "" %>

<style>

  /*====
  Animation 
  ======*/

  @keyframes floatyness {
    50%  { 
      transform: translate3d(0, -10px, 0);
      animation-timing-function: ease-in-out;
    }
    0%, 100% { /* Same starting and ending properties. */
      transform: translate3d(0, 0, 0);
      animation-timing-function: ease-in-out; 
    }
  }

  @keyframes floatyness2 {
    50%  { 
      transform: translate3d(0, 10px, 0);
      animation-timing-function: ease-in-out;
    }
    0%, 100% { 
      transform: translate3d(0, 0, 0);
      animation-timing-function: ease-in-out; 
    }
  }

  @keyframes laserfire {
    0% {
      opacity: 1;
      transform: translate3d(0, 0, 0);
    }
    59% {
      opacity: 1;
    }
    61% {
      opacity: 0;
    }
    62% {
      opacity: 1;
    }
    63% {
      opacity: 0;
    }
    64% {
      opacity: 1;
    }
    65% {
      opacity: 0;
    }
    66% {
      opacity: 1;
    }
    67% {
      opacity: 0;
    }
    68% {
      opacity: 1;
    }
    69% {
      opacity: 0;
    }
    70% {
      opacity: 1;
      transform: translate3d(0, -10px, 0);
    }
  }



  .center-banner {
    position: relative;
    height: 0;
    padding-bottom: 400px;
    margin-bottom: 32px;

    background-color: #6d8ec9;
  }

  @media only screen and (min-width: 300px) {
    .center-banner {
      padding-bottom: 600px;
    }
  }

  @media only screen and (min-width: 500px) {
    .center-banner {
      padding-bottom: 800px;
    }
  }

  /*======================================
    Sir, what the fuck are we looking at?
    Some kind of, ANOMALY!
  =======================================*/

  /* THE */ .anomaly {
    position: absolute;
      top: 0;
      left: 0;
    width: 100%;
    height: 100%;
    margin: 0 auto;
    z-index: 200;
    overflow: hidden;

    display: flex;
    justify-content: center;
  }

  @media only screen and (min-width: 500px) {
    .anomaly {
      padding-top: 50px;
    }
  }

  .anomaly__parts {
    height: 100%;
    width: 100%;
    position: relative;
    transition: 0.2s ease-in-out all;
    transform: scale(0.5);
    min-width: 440px;
  }

  @media only screen and (min-width: 300px) {
    .anomaly__parts {
      transform: scale(0.6);
    }
  }

  @media only screen and (min-width: 500px) {
    .anomaly__parts {
      transform: scale(0.8);
    }
  }

  @media only screen and (min-width: 654px) {
    .anomaly__parts {
      width: 80%;
      transform: scale(1.0);
    }
  }

  @media only screen and (min-width: 1024px) {
    .anomaly__parts {
      width: 50%;
    }
  }

  .anomaly__parts div { /* All parts of the anomaly. */
    position: absolute;
  }

  .anomaly__parts img {
    background: transparent;
  }


  /*====
  The Pieces
  ======*/

  .anomaly__yellow-ball {
    top: 343px;
    left: 548px;

    width: 25px;
    height: 28px;

    z-index: 100;

    animation: floatyness 2s infinite;
  }
  .anomaly__green-ball {
    top: 423px;
    left: 420px;

    z-index: 181; /* In front of the top chunk */
    animation: floatyness2 2.5s infinite;
  }
  .anomaly__anchor {
    top: 608px;
    left: 371px;

    z-index: 191; /* In front of the bottom chunk */
    animation: floatyness2 4s infinite;
  }
  .anomaly__chocolate-drop {
    filter: blur(3px);

    top: 313px;
    left: 420px;

    z-index: 179; /* behind the top chunk. */
    animation: floatyness 7s infinite;
  }
  .anomaly__boat {
    filter: blur(2px);

    top: 190px;
    left: -24px;

    z-index: 183; /* In front of the licorice swoosh */
    animation: floatyness2 7.5s infinite;
  }
  .anomaly__licorice-swoosh {
    filter: blur(1px);

    top: 145px;
    left: 53px;

    z-index: 1082; /* Above the the top chunk but behind the bottom chunk. */
    animation: floatyness2 4.5s infinite;
  }
  .anomaly__crown {
    filter: blur(1px);

    top: 220px;
    left: 378px;
    
    z-index: 181; /* In front of the top chunk */
    animation: floatyness2 4s infinite;
  }
  .anomaly__laser-beam {
    filter: blur(1px);
    top: -134px;
    left: 350px;

    width: 356px;
    height: 256px;

    z-index: 179; /* Behind the top chunk */
    animation: laserfire 8s infinite;
  }
  .anomoly__rock-tunnel {
    top: 240px;
    left: 211px;

    z-index: 200; /* Top of everything */
    animation: floatyness 8s infinite;
  }
  .anomaly__top-chunk {
    filter: blur(1px);

    left: 128px;
    top: 18px;

    width: 376px;
    height: 453px;

    z-index: 180; /* Behind the rock tunnel and the top chunk */
    animation: floatyness 8s infinite;
  }
  .anomaly__bottom-chunk {
    left: 15px;
    top: 183px;

    width: 514px;
    height: 481px;

    z-index: 190; /* Behind the rock tunnel but above the top chunk */
    animation: floatyness 6s infinite;
  }

</style>

<%= render 'shared/work_before' %>


      <header class="c-work-single__header u-spacers">
        <div class="u-space-md">
          <div class="c-article__page-topper">
            Freo Royale: 
            <time datetime="2015">2015</time>
          </div>
        </div>
        <div class="u-space-stack-lg">
          <ul class="c-tag-list">
            <li class="c-tag-list__tag">CSS Animation</li>
            <li class="c-tag-list__tag">Photoshop</li>
          </ul>
          <h1 class="c-work-single__title">Bringing Liam Dee's Artwork to Life</h1>
          <section class="c-work-single__description">
            <p>This was a graphic by <a href="https://www.liamdeeart.com/" title="Liam Dee Artwork Website">Liam Dee</a> as part of the branding for Freo Royale (RIP) which was an offshoot of Fringe World. I saw the graphic as a good opportunity to practice some CSS Animations and Filters.</p>
          </section>
        </div>

        <div class="u-space-md">
          <!-- Banner Image -->
        </div>
      </header>


      <main class="c-work-single__main u-spacers">

        <div class="u-space">

          <div class="center-banner">
            <div class="anomaly">
              <div class="anomaly__parts">
                <div class="anomaly__yellow-ball">
                  <%= image_tag("work/anomaly/yellow-ball.png", alt: "A yellow ball.") %></div>
                <div class="anomaly__green-ball">
                  <%= image_tag("work/anomaly/green-ball.png", alt: "A green ball.") %></div>
                <div class="anomaly__anchor">
                  <%= image_tag("work/anomaly/anchor.png", alt: "An anchor.") %></div>
                <div class="anomaly__chocolate-drop">
                  <%= image_tag("work/anomaly/chocolate-drop.png", alt: "A chocolate drop.") %></div>
                <div class="anomaly__boat">
                  <%= image_tag("work/anomaly/boat.png", alt: "A boat.") %></div>
                <div class="anomaly__licorice-swoosh">
                  <%= image_tag("work/anomaly/licorice-swoosh.png", alt: "Some licorice.") %></div>
                <div class="anomaly__crown">
                  <%= image_tag("work/anomaly/crown.png", alt: "A crown.") %></div>
                <div class="anomaly__laser-beam">
                  <%= image_tag("work/anomaly/laser-beam.png", alt: "A laser beam.") %></div>
                <div class="anomaly__top-chunk">
                  <%= image_tag("work/anomaly/top-chunk.png", alt: "The top part of an illustration.") %></div>
                <div class="anomaly__bottom-chunk">
                  <%= image_tag("work/anomaly/bottom-chunk.png", alt: "The bottom part of an illustration.") %></div>
                <div class="anomoly__rock-tunnel">
                  <%= image_tag("work/anomaly/rock-tunnel.png", alt: "A rock tunnel.") %></div>
              </div><!-- .anomaly__parts -->
            </div><!-- .anamoly -->
          </div><!-- .center-banner -->

        </div>

        <div class="u-space-md">
          <aside class="c-article__colophon">
            <h1>Credits</h1>
            <p>Original artwork by Liam Dee: <a href="http://www.liamdeeart.com/fullscreen-page/comp-j3u3dakw/cb667d2d-5644-4223-9202-8f115f590185/30/%3Fi%3D30%26p%3Dv49ck%26s%3Dstyle-j42n2ic1" title="Link to original artwork by Liam Dee">"Freo Royale 2014", Acrylic on Board, 90cm X 60cm</a></p>
          </aside>
        </div>

      </main>

      <div class="u-spacers">
        <div class="u-space-md l__menu-space-between">
          <%= link_to work_wa_meats_path, class: 'c-button c-button-fluid c-button-icon' do %>
            <i class="c-button-icon__icon fa fa-arrow-left"></i>
            <span class="c-button-icon__text">Prev</span>
          <% end %>
          <%= link_to work_glitched_path, class: 'c-button c-button-fluid c-button-icon' do %>
            <i class="c-button-icon__icon fa fa-arrow-right"></i>
            <span class="c-button-icon__text">Next</span>
          <% end %>
        </div>
      </div>


<%= render 'shared/work_after' %>

app/views/work/glitched.html.erb
<% content_for :body_class, "work-single " %>
<% content_for :title, "Work: Glitched Horror Animation" %>
<% content_for :description, "" %>

<%= render 'shared/work_before' %>


      <header class="c-work-single__header u-spacers">
        <div class="u-space-md">
          <div class="c-article__page-topper">
            Two Of Three: 
            <time datetime="2017">2017</time>
          </div>
        </div>
        <div class="u-space-stack-lg">
          <ul class="c-tag-list">
            <li class="c-tag-list__tag">CSS Animation</li>
          </ul>
          <h1 class="c-work-single__title">Glitched Horror Animation</h1>
          <section class="c-work-single__description">
            <p>This was a fun little project we put together at Two Of Three for one of our home pages. We wanted to make a project we could all work on with our own direction.</p>
          </section>
        </div>
      </header>


      <main class="c-work-single__main u-spacers">

        <div class="u-space">
          <div class="gawy gawy__background">

            <h1 class="gawy__title">Graphics and Websites yo!</h1>

            <div class="gawy__image">

              <div class="gawy__text">
                <div class="gawy__text-ratio">
                  <span class="gawy__text-title"></span>
                  <span class="gawy__text-outlines"></span>
                  <span class="gawy__text-outlines-2"></span>
                  <span class="gawy__text-dropshadow"></span>
                </div>
              </div>


              <div class="gawy__image-computer">
                <div class="gawy__image-computer-ratio">
                  <%= image_tag("work/graphics-websites-yo/1973-BMT-100@2x.png", alt: "An illustration of a 1973 BTM-100 Computer", class: "gawy__image-computer-screen") %>
                  <span class="gawy__image-computer-glow"></span>
                  <span class="gawy__image-computer-glow--static"></span>
                </div>
              </div>


            </div>

          </div>
        </div>

        <div class="u-space-md">
          <aside class="c-article__colophon">
            <h1>Credits</h1>
            <p>For this project I worked on building this for web. Most of the work went into animations and making it responsive.</p>
            <ul>
              <li>Adam Gormley: All computer illustrations including faces, grunge texture.</li>
              <li>Adam Nielsen: Typography and type treatment.</li>
            </ul>
          </aside>
        </div>

      </main>

      <div class="u-spacers">
        <div class="u-space-md l__menu-space-between">
          <%= link_to work_anomaly_path, class: 'c-button c-button-fluid c-button-icon' do %>
            <i class="c-button-icon__icon fa fa-arrow-left"></i>
            <span class="c-button-icon__text">Prev</span>
          <% end %>
          <%= link_to about_site_path, class: 'c-button c-button-fluid c-button-icon' do %>
            <i class="c-button-icon__icon fa fa-arrow-right"></i>
            <span class="c-button-icon__text">About This Site</span>
          <% end %>
        </div>
      </div>


<%= render 'shared/work_after' %>